name: White Rabbit

servies:
  - name: infrastructure
    version: 0.1.6
    order: 0
  - name: monitoring
    version: 1.1.0
    order: 1
  - name: engine
    version: 1.4.6
    order: 2
    parameters:
      someValue: override
      replicas: 5
  - name: test
    version: 0.5.5
    order: 2
  - name: ui
    version: 2.6.9
    order: 2
  - name: worker
    version: 5.1.0
    order: 2