apiVersion: v2
name: migration
description: Basic migration mechanism
type: application
version: 2.1.0
appVersion: 2.1.0

dependencies:
- name: common
  version: 0.1.2
  repository: "https://example.com/charts"
