parameters:
- name: param
  type: string

jobs:
- job: PR
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: blocks/bundle.yml
    parameters:
      param: ${{ parameters.param }}

  - template: blocks/delete.yml
    parameters:
      param: ${{ parameters.param }}